repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff-format
        name: ruff format
        types: [python]
      - id: ruff
        name: ruff check
        args: [--fix]
        types: [python]

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        name: djlint reformat
        types: [html]
      - id: djlint-django
        name: djlint check
        types: [html]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier
        types_or: [css, javascript]
